package com.fq.rule.file;
/**
 * 文件命名规则枚举类
 * @author MaiBenBen
 *
 */
public enum FileNameRuleEnum{
	
	ACTOR_REPORT , USER_REPORT , MOVIE_REPORT , PROJECT_REPORT , ADD_HEAL_REPORT ,
	
	GIFT_PICTURE , LOG_PICTURE , LOG_MOVIE  , MOVIE , MOVIE_COVER , PROJECT_COVER , 
	
	PROJECT_CREW_COVER , ALBUM ,START_PAGE , ALL_PROJECT_REPORT , PROJECT_ORIGINAL_COVER , 
	
	LIVE_CARTOON_PICTURE,MOVIE_PAPA_REPORT,TRADE_CONSUME_REPORT , WEEK_TRADE_CONSUME_REPORT ,
	
	TRADE_INFO_REPORT  , ACTIVE_AWARD_REPORT, ACTIVE_URL  ,ACTIVE_SUCC_URL , UNLOCK_LIVE_CARTOON  ,
	
	OSCAR_ACTIVE_URL  , OSCAR_ACTIVE_VOTE_URL	, ACTIVE_BGI_TWO	,   ACTIVE_BGI_THREE  , 
	
	HIS_TRADE_INFO_REPORT , BUY_VOTE_REPORT , VOTE_LOG_REPORT , GIVE_VOTE_REPORT , USER_INFO , CARTOON_REPORT ,
	
	BULLET_SCREEN , NEW_USER , USER_MOBILE  , NOVEL_REPORT  , NOVEL_MONTH_REPORT  , NOVEL_DAY_REPORT  
	
	;
	
}