package com.cz.coder.common.constant;

public enum RetCodeEnum {

	SUCCESS("0","成功"),
	
	NOT_POST( RetCode.NOT_POST , "访问方式必须为POST" ),                                                   
	WRONG_MOBILENUM( RetCode.WRONG_MOBILENUM , "账户不存在或密码错误" ) ,                                            
	WRONG_PASSWORD( RetCode.WRONG_PASSWORD , "账户或密码错误" ) ,                                                
	LOSE_TOKEN( RetCode.LOSE_TOKEN , "TOKEN失效" ) ,                                                    
	TOO_MORE_MOBLE_CODE_REQUEST( RetCode.TOO_MORE_MOBLE_CODE_REQUEST , "过于频繁的手机验证码请求" ) ,                              
	SEND_CREATE_MOBLE_CODE_FAIL( RetCode.SEND_CREATE_MOBLE_CODE_FAIL , "发送短息验证码失败" ) ,                                 
	UPLOAD_FILE_FAILED( RetCode.UPLOAD_FILE_FAILED , "上传文件失败" ) ,                                             
	DATABASE_EXCEPTION( RetCode.DATABASE_EXCEPTION , "数据库异常" ) ,                                              
	MOBILE_CODE_CHECK_WRONG( RetCode.MOBILE_CODE_CHECK_WRONG , "手机验证码错误" ) ,                                       
	MOBILE_CODE_CREATE_ERROR( RetCode.MOBILE_CODE_CREATE_ERROR , "手机验证码生成失败" ) ,                                    
	MOBILE_EXISTS( RetCode.MOBILE_EXISTS , "注册用户已存在" ) ,                                                 
	UNSUPPORT_FILE_SUFFIX( RetCode.UNSUPPORT_FILE_SUFFIX , "不支持的图片格式格式" ) ,                                      
	RONGCLOUD_ACCESS_ERROR( RetCode.RONGCLOUD_ACCESS_ERROR , "融云服务器请求失败" ) ,                                      
	RONGCLOUD_GET_TOKEN_FAIL( RetCode.RONGCLOUD_GET_TOKEN_FAIL , "获取融云TOKEN失败" ) ,                                  
	LOST_PARAM( RetCode.LOST_PARAM , "请求数据缺失" ) ,                                                     
	PARAMS_PARAM( RetCode.PARAMS_PARAM , "请求参数错误" ) ,                                                   
	GET_PLAY_URL_ERROR( RetCode.GET_PLAY_URL_ERROR , "获取播放地址失败") ,                                            
	DATA_ERROR( RetCode.DATA_ERROR , "数据异常" ) ,                                                       
	MOBILE_IS_NONE( RetCode.MOBILE_IS_NONE , "无匹配的结果" ) ,                                                 
	IMGS_NUM( RetCode.IMGS_NUM , "图片数量过多" ) ,                                                       
	WRONG_SEX( RetCode.WRONG_SEX , "性别输入有误" ) ,                                                      
	SYSTEM_ERROR( RetCode.SYSTEM_ERROR , "系统异常" ) ,                                                     
	REDIS_LIMIT_ACCESS_PREMISSION( RetCode.REDIS_LIMIT_ACCESS_PREMISSION, "redis 没有访问权限"),                               
	ACCT_NULL( RetCode.ACCT_NULL , "查询结果为空" ) ,                                                      
	WRONG_PARAM( RetCode.WRONG_PARAM , "参数无效"),                                                        
	GET_IMG_URL_ERROR( RetCode.GET_IMG_URL_ERROR , "获取图片URL失败"),                                             
	TOPIC_IS_NOT_VISIBLE( RetCode.TOPIC_IS_NOT_VISIBLE , "该话题已被删除"),                                            
	USER_IS_NOT_VISIBLE( RetCode.USER_IS_NOT_VISIBLE , "该用户不存在"),                                              
	USER_DOES_NOT_HAVE_PERMISSIONS( RetCode.USER_DOES_NOT_HAVE_PERMISSIONS , "用户没有相关权限"),                                 
	USER_IS_ALREADY_EXISTS( RetCode.USER_IS_ALREADY_EXISTS , "该用户已存在"),                                           
	MOVIE_IS_NOT_EXISTS( RetCode.MOVIE_IS_NOT_EXISTS  , "该影片已被作者删除"),                                          
	MOVIE_IS_COLLECTED( RetCode.MOVIE_IS_COLLECTED  , "该影片已收藏"),                                              
	MOVIE_IS_NOT_COLLECTED( RetCode.MOVIE_IS_NOT_COLLECTED  , "该影片未收藏"),                                          
	MOVIE_IS_LIKED( RetCode.MOVIE_IS_LIKED  , "该影片已点赞"),                                                  
	MOVIE_IS_NOT_LIKED( RetCode.MOVIE_IS_NOT_LIKED  , "该影片未点赞"),                                              
	CAN_NOT_REATTENTION( RetCode.CAN_NOT_REATTENTION  , "不能重复关注"),                                             
	IS_NOT_ATTENTION( RetCode.IS_NOT_ATTENTION  , "未关注该用户"),                                                
	CAN_NOT_REWARD_USERSELF( RetCode.CAN_NOT_REWARD_USERSELF  , "用户不能打赏自己"),                                       
	USER_HEAD_IS_NULL( RetCode.USER_HEAD_IS_NULL  , "用户上传头像为空"),                                             
	USER_JPOINT_IS_NOT_FULL( RetCode.USER_JPOINT_IS_NOT_FULL  , "用户余额不足"),                                         
	CAN_NOT_REPLY_USERSELF( RetCode.CAN_NOT_REPLY_USERSELF, "用户不能回复自己"),                                           
	PROJECT_IS_NULL( RetCode.PROJECT_IS_NULL, "项目不存在"),                                                     
	COMMENT_IS_NULL( RetCode.COMMENT_IS_NULL, "评论不存在"),                                                     
	HOT_COMMENT_IS_NULL( RetCode.HOT_COMMENT_IS_NULL, "暂无热门评论"),                                                
	COMMENT_MISS( RetCode.COMMENT_MISS, "评论失败"),                                                         
	IS_PRAISE( RetCode.IS_PRAISE, "不能重复点赞"),                                                          
	IS_NOT_PRAISE( RetCode.IS_NOT_PRAISE, "该用户还没有点赞"),                                                    
	USER_PRAISE_ERROR( RetCode.USER_PRAISE_ERROR, "操作无效"),                                                    
	PROJECT_LOG_DOSE_NOT_EXISTS( RetCode.PROJECT_LOG_DOSE_NOT_EXISTS, "该帖子已被删除"),                                       
	PROJECT_LOG_POST_COMMENT_ERROR( RetCode.PROJECT_LOG_POST_COMMENT_ERROR, "项目日志评论发表失败"),                                 
	PROJECT_LOG_COMMENT_DOES_NOT_EXISTS( RetCode.PROJECT_LOG_COMMENT_DOES_NOT_EXISTS, "项目日志评论不存在"),                             
	PROJECT_IS_HEAL_FULL( RetCode.PROJECT_IS_HEAL_FULL, "项目加血已经结束"),                                             
	HEAL_AMOUNT_ERROR( RetCode.HEAL_AMOUNT_ERROR, "加血量不能小于0"),                                                
	BULLET_SCREEN_CAN_NOT_REPEAT_SEND( RetCode.BULLET_SCREEN_CAN_NOT_REPEAT_SEND, "30s内弹幕不可重复发送"),                            
	CDKEY_IS_NULL( RetCode.CDKEY_IS_NULL, "该兑换码不存在"),                                                     
	LOST_CDKEY( RetCode.LOST_CDKEY, "该兑换码已领取过"),                                                       
	ERROR_MORE_THAN_TEN( RetCode.ERROR_MORE_THAN_TEN, "输入错误次数超过10次 。 请明天再试"),                                   
	HEAL_CANNOT_UNDER_LIMIT( RetCode.HEAL_CANNOT_UNDER_LIMIT ,  "加血量不能低于下限" ) ,                                     
	CAN_NOT_ATTENTION_YOURSELF( RetCode.CAN_NOT_ATTENTION_YOURSELF , "你这个自恋狂，关注自己干嘛!!!!"),                             
	USER_NICK_IS_ALREADY_EXISTS( RetCode.USER_NICK_IS_ALREADY_EXISTS , "该用户名已被使用了哦，再换一个吧"),                             
	CAN_NOT_RECOMMENT( RetCode.CAN_NOT_RECOMMENT , "宝宝反应慢稍等一下啦~十秒之内请勿多次点击，谢谢啦~~~"),                           
	QINIU_SERVER_ERROR( RetCode.QINIU_SERVER_ERROR, "七牛服务异常"),                                                 
	QINIU_RESOURCE_SUFFIX_WRONG( RetCode.QINIU_RESOURCE_SUFFIX_WRONG, "资源类型错误"),                                        
	CANNOT_NULL( RetCode.CANNOT_NULL, "不能为空"),                                                          
	ADMIN_HAS_EXISTS( RetCode.ADMIN_HAS_EXISTS, "账号已经存在") ,                                                  
	ROLE_HAS_EXISTS( RetCode.ROLE_HAS_EXISTS, "角色已经存在"),                                                    
	LOGIN_BY_QQ_ERROR( RetCode.LOGIN_BY_QQ_ERROR , "qq登陆失败"),                                                 
	LOGIN_BY_WEIXIN_ERROR( RetCode.LOGIN_BY_WEIXIN_ERROR , "微信登陆失败"),                                             
	LOGIN_BY_WEIBO_ERROR( RetCode.LOGIN_BY_WEIBO_ERROR, "微博登陆失败"),                                               
	PIC_URL_ERROR( RetCode.PIC_URL_ERROR, "无效头像链接！！"),                                                    
	REDIS_IS_READONLY( RetCode.REDIS_IS_READONLY, "访问REDIS是只读的"),                                             
	REDIS_CANNOT_OPEN_CONNECTION( RetCode.REDIS_CANNOT_OPEN_CONNECTION, "无法连接到指定的redis") ,                               
	REDIS_ACCESS_REDIS_SERVER_ERROR( RetCode.REDIS_ACCESS_REDIS_SERVER_ERROR, "访问redis服务器失败") ,                             
	PRODUCT_IS_NOT_EXIST( RetCode.PRODUCT_IS_NOT_EXIST, "商品不存在"),                                                
	REDIS_ACCESS_ALL_SERVER_ERR( RetCode.REDIS_ACCESS_ALL_SERVER_ERR, "所有redis服务访问异常"),                                 
	USER_CHASE_PROJECT_ERROR( RetCode.USER_CHASE_PROJECT_ERROR,"操作无效"),                                              
	GIFT_IS_NOT_EXISTS( RetCode.GIFT_IS_NOT_EXISTS,"该礼品已下架"),                                                  
	USER_IS_NOT_IN_CREW( RetCode.USER_IS_NOT_IN_CREW,"用户不在剧组成员中"),                                              
	GIFT_GIVING_NOT_EXISTS( RetCode.GIFT_GIVING_NOT_EXISTS,"礼单不存在"),                                               
	LIKING_REL_NOT_EXITS( RetCode.LIKING_REL_NOT_EXITS,"好感关系不存在"),                                               
	WRONG_DATE_FORMAT( RetCode.WRONG_DATE_FORMAT, "时间格式不正确") ,                                                
	COMMON_START_PAGE_NULL( RetCode.COMMON_START_PAGE_NULL, "启动页无更新") ,                                            
	QINIU_RESOURCE_TYPE_WRONG( RetCode.QINIU_RESOURCE_TYPE_WRONG, "未选择资源分类"),                                         
	QINIU_SERVER_ERROR_URL( RetCode.QINIU_SERVER_ERROR_URL, "该图片路径地址不靠谱,请用本地文件上传！"),                               
	CREATE_QINIU_TOKEN_ERROR( RetCode.CREATE_QINIU_TOKEN_ERROR, "获取七牛TOKEN失败！"),                                     
	ACCESS_MAGICWINDOW_API_ERROR( RetCode.ACCESS_MAGICWINDOW_API_ERROR, "访问魔窗接口失败！"),                                    
	TASK_INFO_IS_NULL( RetCode.TASK_INFO_IS_NULL, "暂时没有新的任务"),                                                
	EXCHANGE_ERROR( RetCode.EXCHANGE_ERROR, "剧点兑换失败"),                                                     
	EXCHANGE_ERROR_REPEAT_RECEIVE( RetCode.EXCHANGE_ERROR_REPEAT_RECEIVE, "已经领取过了哦~"),                                    
	ACTIVITY_IS_NOT_VISIBLE( RetCode.ACTIVITY_IS_NOT_VISIBLE, "活动已过期"),                                             
	CDKEY_NOT_YET_STARTED( RetCode.CDKEY_NOT_YET_STARTED, "还未到兑换日期"),                                             
	CDKEY_OUT_OF_DATE( RetCode.CDKEY_OUT_OF_DATE, "兑换已经结束"),                                                  
	PROJECT_LIVE_CARTOON_IS_NULL( RetCode.PROJECT_LIVE_CARTOON_IS_NULL, "真人漫画还在制作中"),                                    
	LIVE_CARTOON_IS_NULL( RetCode.LIVE_CARTOON_IS_NULL, "该集还在制作中"),                                              
	LIVE_CARTOON_HAVE_CHASED( RetCode.LIVE_CARTOON_HAVE_CHASED, "用户已经追过了"),                                          
	LIVE_CARTOON_HAVE_NOT_CHASED( RetCode.LIVE_CARTOON_HAVE_NOT_CHASED, "用户还没有追呢"),                                      
	LIVE_CARTOON_HAVE_PERMISION( RetCode.LIVE_CARTOON_HAVE_PERMISION, "解锁啦！磕头咚咚"),                                      
	LIVE_CARTOON_HAVE_NO_PERMISION( RetCode.LIVE_CARTOON_HAVE_NO_PERMISION, "您还没有解锁哦"),                                    
	LIVE_CARTOON_DUBBING_IS_NULL( RetCode.LIVE_CARTOON_DUBBING_IS_NULL, "配音信息不存在"),                                      
	LIVE_CARTOON_DUBBING_HAVE_NO_PERMISION( RetCode.LIVE_CARTOON_DUBBING_HAVE_NO_PERMISION, "您不能修改别人的配音信息哦"),                      
	LIVE_CARTOON_LOCATION_IS_USELESS( RetCode.LIVE_CARTOON_LOCATION_IS_USELESS, "亲，配音错位了呢~赶快放到正确的位置吧"),                      
	CDKEY_BEYOND_LIMIT( RetCode.CDKEY_BEYOND_LIMIT, "不能重复使用哦"),                                                
	ORDER_NOT_EXISTS( RetCode.ORDER_NOT_EXISTS, "订单信息不存在，请核实订单信息"),                                          
	ORDER_SUPPLEMENT_FAILED( RetCode.ORDER_SUPPLEMENT_FAILED, "补单申请失败，点击申诉，宝宝别急48小时内肯定处理哟！"),                       
	ORDER_ALREADY_FINISHED( RetCode.ORDER_ALREADY_FINISHED, "订单已完成" ),                                             
	ORDER_PINGPP_PAID_FAILED( RetCode.ORDER_PINGPP_PAID_FAILED, "pingpp订单未支付" ),                                     
	ORDER_IOS_FAILED( RetCode.ORDER_IOS_FAILED, "IOS订单暂时不能对账" ),                                             
	PROJECT_WALLPAPER_NOT_EXISTS( RetCode.PROJECT_WALLPAPER_NOT_EXISTS, "壁纸信息不存在" ),                                     
	MOVIE_NODE_IS_NOT_EXISTS( RetCode.MOVIE_NODE_IS_NOT_EXISTS, "影片节点信息不存在" ),                                       
	USER_INVITE_CODE_IS_INVALID( RetCode.USER_INVITE_CODE_IS_INVALID, "此兑换码已失效" ),                                      
	USER_INVITE_CODE_IS_BEYOND( RetCode.USER_INVITE_CODE_IS_BEYOND, "此兑换码今天用不了呢明天来试试吧" ),                              
	USER_INVITE_CODE_SAME_EQUIPMENT( RetCode.USER_INVITE_CODE_SAME_EQUIPMENT, "同一台手机不能多次操作哦" ),                             
	USER_INVITE_CODE_IS_INVITED( RetCode.USER_INVITE_CODE_IS_INVITED, "亲你已经被邀请过了" ),                                    
	USER_INVITE_CODE_THEMSELF( RetCode.USER_INVITE_CODE_THEMSELF, "不能使用自己的兑换码哦" ),                                    
	USER_IS_REFUSE( RetCode.USER_IS_REFUSE, "该账户已被封号，请不要散发垃圾信息" ),                                         
	USER_IS_GAG( RetCode.USER_IS_GAG, "该账户已被禁言，请不要散发垃圾信息" ),                                            
	NOTIFICATION_IS_NOT_VISIABLE( RetCode.NOTIFICATION_IS_NOT_VISIABLE, "该消息已不存在" ),                                     
	NOTIFICATION_REPLY_MSG_OUT_OF_RANG( RetCode.NOTIFICATION_REPLY_MSG_OUT_OF_RANG, "该消息内容太长" ),                               
	NOTIFICATION_HAVE_REPLIED( RetCode.NOTIFICATION_HAVE_REPLIED, "该消息已回复过" ),                                        
	QUESTION_IS_NOT_VISIBLE( RetCode.QUESTION_IS_NOT_VISIBLE, "问卷信息不存在" ),                                          
	QUESTION_IS_OUT_OF_DATE( RetCode.QUESTION_IS_OUT_OF_DATE, "本页面超时已过期" ),                                         
	QUESTION_CAN_NOT_CHANGE( RetCode.QUESTION_CAN_NOT_CHANGE, "答案不许修改哦" ),                                          
	QUESTION_ANSWER_LENGTH_TOO_LONG( RetCode.QUESTION_ANSWER_LENGTH_TOO_LONG, "答案字数太长" ),                                   
	QUESTION_ANSWER_LENGTH_TOO_SHOT( RetCode.QUESTION_ANSWER_LENGTH_TOO_SHOT, "答案字数太短" ),                                   
	QUESTION_ANSWER_SIZE_NOT_ENOUGH( RetCode.QUESTION_ANSWER_SIZE_NOT_ENOUGH, "答案不完整呢，再想想~~" ),                             
	OSCAR_ACTIVE_IS_NOT_VISIBLE( RetCode.OSCAR_ACTIVE_IS_NOT_VISIBLE, "活动信息不存在" ),                                      
	OSCAR_ACTIVE_IS_OUT_OF_DATE( RetCode.OSCAR_ACTIVE_IS_OUT_OF_DATE, "活动已截至" ),                                        
	OSCAR_ACTIVE_ACTOR_IS_NOT_VISIBLE( RetCode.OSCAR_ACTIVE_ACTOR_IS_NOT_VISIBLE, "候选人信息不存在" ),                               
	OSCAR_ACTIVE_VOTE_IS_NOT_VISIBLE( RetCode.OSCAR_ACTIVE_VOTE_IS_NOT_VISIBLE , "选票无效") ,                                   
	OSCAR_ACTIVE_ACTOR_CANNOT_SEND_VOTE_TO_OTHERS( RetCode.OSCAR_ACTIVE_ACTOR_CANNOT_SEND_VOTE_TO_OTHERS, "候选人员之间不能互相赠送选票" ),             
	ACTIVE_DEVICE_IS_USED( RetCode.ACTIVE_DEVICE_IS_USED, "同一个手机设备只能领取一次" ),                                      
	ACTIVE_MOBILE_IS_USED( RetCode.ACTIVE_MOBILE_IS_USED, "同一个手机号只能领取一次" ),                                       
	ACTIVE_ACCOUNT_IS_USED( RetCode.ACTIVE_ACCOUNT_IS_USED, "同一个用户账号只能领取一次" ),                                     
	ACTIVE_IS_NOT_VISIABLE( RetCode.ACTIVE_IS_NOT_VISIABLE, "活动信息不存在" ),                                           
	ACTIVE_ONLY_NEW_REGISTER( RetCode.ACTIVE_ONLY_NEW_REGISTER, "此活动只针对新注册用户哦！" ),                                   
	PROJECT_LOG_RESOURCE_TITLE_TOO_LONG( RetCode.PROJECT_LOG_RESOURCE_TITLE_TOO_LONG, "资源帖标题过长" ),
	BATCHTASK_STATE_WRONG(RetCode.BATCHTASK_STATE_WRONG,"任务状态不正确");
	
	private String code ;
	private String codeMsg ;
	
	private RetCodeEnum(String code , String codeMsg){
		this.code = code ;
		this.codeMsg = codeMsg ;
	}

	public String getCode() {
		return code;
	}

	public String getCodeMsg() {
		return codeMsg;
	}
	
}
